docs: rego rule explanation and links
stackabletech/hdfs-operator pull request #519
Opened 2024-05-03 13:06 UTC by adwk67

# Description

fixes https://github.com/stackabletech/hdfs-operator/issues/516.

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes
 
```[tasklist]
# Author
- [ ] Link to hdfs-utils repo
- [ ] Link to integration tests folder
- [ ] Provide a short example and explanation of the example
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-05-06 06:39 UTC, sbernauer approved these changes, later dismissed
This exceeds what I expected to document, so many thanks :)

I'm not 100% sure if we want to link to the rego rules in hdfs-utils *and* integration tests. I think it's a bit easier to only have a single source of truth - which needs to be the integration test to align with trino-operator

2024-05-06 06:39 UTC, sbernauer commented on docs/modules/hdfs/pages/usage-guide/security.adoc
> +We provide a more representative rego rule in our integration tests and in the afore-mentioned hdfs-utils repository.
Had to google this word, IDK if this is correct
```suggestion
We provide a more representative rego rule in our integration tests and in the aforementioned hdfs-utils repository.
```

2024-05-06 07:44 UTC, adwk67 commented
> This exceeds what I expected to document, so many thanks :)
> 
> I'm not 100% sure if we want to link to the rego rules in hdfs-utils _and_ integration tests. I think it's a bit easier to only have a single source of truth - which needs to be the integration test to align with trino-operator

Yes, good point. I'd quite like to keep the reference to `hdfs_test.rego` in there, which refers to the rego rule in hdfs-utils. I can maybe just use it in-line and remove the link to hdfs-utils. What do you think?

2024-05-07 07:10 UTC, sbernauer commented
Ahh I see the point of including the test :+1: Yep, that suggestion sounds good to me :+1:

2024-05-08 12:54 UTC, fhennig requested changes, later dismissed

2024-05-08 12:54 UTC, fhennig commented on docs/modules/hdfs/pages/usage-guide/security.adoc
> +=== Fine-granular rego rule
```suggestion
[#fine-granular-rego-rules]
=== Fine-granular rego rules
```

2024-05-08 12:54 UTC, fhennig commented on docs/modules/hdfs/pages/usage-guide/security.adoc
> +Details can be found below in the <<_fine_granular_rego_rule_, fine-granular rego rule>> section.
```suggestion
Details can be found below in the <<fine-granular-rego-rules, fine-granular rego rules>> section.
```

2024-05-08 12:54 UTC, fhennig commented on docs/modules/hdfs/pages/usage-guide/security.adoc
> +With a few minor differences (e.g. pod names) it is the same rego rule that is used in this https://github.com/stackabletech/hdfs-operator/blob/main/tests/templates/kuttl/kerberos/12-rego-rules.txt.j
```suggestion
With a few minor differences (e.g. Pod names) it is the same rego rule that is used in this https://github.com/stackabletech/hdfs-operator/blob/main/tests/templates/kuttl/kerberos/12-rego-rules.txt.j2[integration test].
```

2024-05-10 06:42 UTC, sbernauer commented
> Yes, good point. I'd quite like to keep the reference to hdfs_test.rego in there, which refers to the rego rule in hdfs-utils. I can maybe just use it in-line and remove the link to hdfs-utils. What do you think?

Thinking about this, in trino-operator we have [the rego rules *and* the tests](https://github.com/stackabletech/trino-operator/tree/main/tests/templates/kuttl/opa-authorization/trino_rules). We could copy/paste the approach to [hdfs-operator](https://github.com/stackabletech/hdfs-operator/tree/main/tests/templates/kuttl/kerberos), so that we can link to rego rules and tests with a single link

2024-05-13 07:56 UTC, adwk67 commented
> I can volunteer to copy the setup from trino to hdfs, pls ping me if I should do it in this branch

That would be great @sbernauer : thank you!

2024-05-16 11:26 UTC, sbernauer approved these changes
> I can volunteer to copy the setup from trino to hdfs, pls ping me if I should do it in this branch

After spending quite some time on it I think I would drop this. In comparison to trino we need to a.) run jinja template and b.) substitute the namespace when applying.
When doing all of this we loose the benefit of being to `opa test` it...

So I would say it's totally fine to link to the integration test for the source of truth of rego rules (they are nightly tested) and link to hdfs-utils for the rego rule tests in case someone is interested

2024-05-16 14:39 UTC, merged