feat: Support non-default cluster domain
stackabletech/hdfs-operator pull request #591
Opened 2024-10-18 09:00 UTC by sbernauer

# Description

Part of https://github.com/stackabletech/issues/issues/652

- [ ] grepped for cluster.local and fixed
- [ ] changelog (if needed)
- [ ] values.yaml comment

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-10-21 08:09 UTC, maltesander requested changes
LGTM otherwise!

2024-10-21 08:09 UTC, maltesander commented on deploy/helm/hdfs-operator/values.yaml
> +# When running on a non-default Kubernetes cluster domain and the auto detections is not working correctly,
```suggestion
# When running on a non-default Kubernetes cluster domain and the auto detection is not working correctly,
```

2024-10-23 12:34 UTC, maltesander requested changes

2024-10-23 12:34 UTC, maltesander commented on deploy/helm/hdfs-operator/values.yaml
> +# kubernetesClusterDomain: my-cluster.local
```suggestion
# When running on a non-default Kubernetes cluster domain, the cluster domain can be configured here.
# See the https://docs.stackable.tech/home/stable/guides/kubernetes-cluster-domain guide for details.
# kubernetesClusterDomain: my-cluster.local
```

2024-10-23 12:34 UTC, maltesander commented on rust/operator-binary/src/config.rs
> +                    nn.fqdn(cluster_info),
Just a nit: lets do it consistent and use the identifiers instead of relying on order?

2024-10-23 12:41 UTC, sbernauer commented on rust/operator-binary/src/config.rs
> +                    nn.fqdn(cluster_info),
Pls have a look at 09caef5

2024-10-23 12:49 UTC, maltesander approved these changes
LGTM!

2024-10-23 12:58 UTC, merged