feat: Support configuring JVM arguments
stackabletech/hdfs-operator pull request #636
Opened 2024-12-27 10:48 UTC by sbernauer

# Description

Part of https://github.com/stackabletech/issues/issues/584

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs/style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-12-27 11:30 UTC, sbernauer commented
Quick smoke test: https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/14/

2025-01-28 15:24 UTC, maltesander requested changes
Only minor things, LGTM otherwise.

2025-01-28 15:24 UTC, maltesander commented on CHANGELOG.md
> +- Set the JVM argument `-Xms` in addition to `-Xmx` (with the same value). This ensure consistent JVM configs across our products.
```suggestion
- Set the JVM argument `-Xms` in addition to `-Xmx` (with the same value). This ensure consistent JVM configs across our products ([#636]).
```

2025-01-28 15:24 UTC, maltesander commented on rust/crd/src/lib.rs
> +                >,
Wanted to suggest type alias but
```
`impl Trait` in type aliases is unstable
see issue #63063 <https://github.com/rust-lang/rust/issues/63063>
```

2025-01-28 15:24 UTC, maltesander commented on rust/operator-binary/src/config/jvm.rs
> +    // Please feel absolutely free to change this behavior!
```suggestion
    // We do *not* add user overrides to the global JVM args, but only the role specific JVM arguments.
    // This allows users to configure stuff for the server (probably what they want to do), without
    // also influencing e.g. startup scripts.
    //
    // However, this is just an assumption. If it is wrong users can still envOverride the global
    // JVM args.
    //
    // Please feel absolutely free to change this behavior!
```

2025-01-28 15:24 UTC, maltesander commented on rust/operator-binary/src/config/jvm.rs
> +    }
Might want to use `construct_global_jvm_args` here or at the start? Otherwise you can move `construct_global_jvm_args`down to the tests section.

2025-01-28 15:24 UTC, maltesander commented on rust/operator-binary/src/config/jvm.rs
> +        jvm_args.push("-Djava.security.krb5.conf=/stackable/kerberos/krb5.conf".to_owned());
Not your doing, but can we make `/stackable/kerberos/` a constant? Its used in container.rs as well a couple of times for env vars etc.

2025-01-28 15:32 UTC, sbernauer commented
Started https://testing.stackable.tech/view/02%20Operator%20Tests%20(custom)/job/hdfs-operator-it-custom/20/

2025-01-28 15:37 UTC, sbernauer commented on rust/crd/src/lib.rs
> +                >,
Well that's a pity

2025-01-28 15:42 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +    }
I *think* it's mostly a coincidence that the global args match this specific arg.
There might be a case in the future that the cli tools/zkfc/format- namenodes need some different arguments than the server.
Or that Kerberos in the server configures more stuff than the cli tools.

2025-01-28 15:45 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +    }
`construct_global_jvm_args` ends up in `HADOOP_OPTS`, so not a test-only thing.
`construct_role_specific_jvm_args` ends up in e.g. `HDFS_NAMENODE_OPTS`

2025-01-28 15:47 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +        jvm_args.push("-Djava.security.krb5.conf=/stackable/kerberos/krb5.conf".to_owned());
It was actually my doing :D I personally intentionally decided against templating it everywhere to avoid complexity. However, I will push a commit to template it

2025-01-28 15:55 UTC, sbernauer commented on rust/operator-binary/src/config/jvm.rs
> +        jvm_args.push("-Djava.security.krb5.conf=/stackable/kerberos/krb5.conf".to_owned());
61345c4

2025-01-28 15:56 UTC, maltesander commented on rust/operator-binary/src/config/jvm.rs
> +        jvm_args.push("-Djava.security.krb5.conf=/stackable/kerberos/krb5.conf".to_owned());
I think i rather template and have it consistent, but leave it up to you :)

2025-01-28 16:03 UTC, maltesander approved these changes
LGTM if test passes!

2025-01-29 08:01 UTC, sbernauer commented
Tests passed :rocket:

2025-01-29 08:10 UTC, merged